### ISSUE TITLE
Documentation Improvement request

### ISSUE THREAD

**Issue by zfarrell** [bkuhl/game-watcher#1]
hey @bkuhl - i'm having a hard time understanding how game-watcher is utilized. 

I understand the purpose of game-watcher, but it's not clear if this lives in travis ci somehow, or needs to be hosted on some external server. It might help to expand the README to include instructions of how (specifically _where_) to run this.

Thanks!

**Comment by bkuhl** [comment]
Sure - the reason there isn't documentation on this yet is that there hasn't yet been a release of this service.  The intended deployment path is that this service will be deployed as a docker container, requiring a few environment variables to operate.  I'm hoping to have this deploy-ready soon.

**Comment by bkuhl** [comment]
Docs have been improved and I've released v1.0.
